---
# tasks file for mysql-db

   - name: install MYSQL-python 
     yum: name=MySQL-python
  
   - name: copy my.cnf file 
     copy: src=my.cnf dest=/root/.my.cnf mode=0600
 
   - name: Set mysql user password
     mysql_user: name=mysql host="{{ item }}" password="{{ mysql_password }}" priv=*.*:ALL
     with_items:
        - "localhost"
        - "127.0.0.1"
        - "::1"
        - "{{ ansible_fqdn }}"
