---
   - name: install MYSQL-python
     yum: name=MySQL-python

   - name: Ensure MYSQL service is started
     action: service name=mysql state=started

   - name: copy my.cnf file
     copy: src=my.cnf dest=/root/.my.cnf mode=0600 owner=root

   - name: update root user password
     mysql_user: name=root host="{{ item }}" password="{{ mysql_root_password }}" priv=*.*:ALL
     with_items:
        - "{{ ansible_fqdn }}"
        - "localhost"
        - "127.0.0.1"
        - "::1"

   - name: Ensure anonymous users are not in the database
     mysql_user: name='' host={{ item }} state=absent
     with_items:
       - localhost
       - "{{ inventory_hostname }}"
